# Generated by Django 5.0.1 on 2024-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login1', models.CharField(max_length=50)),
                ('password1', models.IntegerField()),
            ],
        ),
    ]
