# Generated by Django 5.0.1 on 2024-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize', '0002_base_name_alter_base_login1_alter_base_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='login1',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='base',
            old_name='password1',
            new_name='password',
        ),
    ]
