# Generated by Django 5.0.1 on 2024-03-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize', '0003_rename_login1_baza_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('id_Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synchronize.chat')),
            ],
        ),
    ]
