# Generated by Django 5.0.1 on 2024-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baza',
            name='login1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='baza',
            name='password1',
            field=models.CharField(max_length=20),
        ),
    ]
